server {
    listen		2283 ssl http2;

    # SSL
    ssl_certificate     /cft/server.crt;
    ssl_certificate_key /cft/server.key;

    location / {
        proxy_pass            http://immich-server:2283;
        proxy_set_header Host $host;
        include               nginxconfig.io/proxy.conf;
        add_header Cache-Control "no-cache" always;
        include             nginxconfig.io/security.conf;
    }
}

server {
    listen      2283;
    return      301 https://$host$request_uri;
}
